DROP TABLE IF EXISTS contacts;

CREATE TABLE contacts (
  contact_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name character varying(255) NOT NULL,
  middle_name character varying(255),
  last_name character varying(255) NOT NULL,
  display_name character varying(255) NOT NULL,
  street_address text NOT NULL,
  city character varying(255) NOT NULL,
  region character varying(255) NOT NULL,
  postal_code character varying(255) NOT NULL,
  country character varying(255) NOT NULL,
  phone_number character varying(255),
  email_address character varying(255)
);
