DROP TABLE IF EXISTS contact_tags;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS tags;

CREATE TABLE contacts (
  contact_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name character varying(255) NOT NULL,
  middle_name character varying(255),
  last_name character varying(255) NOT NULL,
  display_name character varying(255) NOT NULL,
  street_address text NOT NULL,
  city character varying(255) NOT NULL,
  region character varying(255) NOT NULL,
  postal_code character varying(255) NOT NULL,
  country character varying(255) NOT NULL,
  phone_number character varying(255),
  email_address character varying(255)
);

CREATE TABLE tags (
  tag_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag_name character varying(255) NOT NULL UNIQUE
);

CREATE TABLE contact_tags (
  contact_id integer REFERENCES contacts (contact_id) ON DELETE CASCADE,
  tag_id integer REFERENCES tags (tag_id) ON DELETE CASCADE,
  PRIMARY KEY (contact_id, tag_id)
);
